DROP TABLE IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS (ID INT AUTO_INCREMENT PRIMARY KEY, NUMERO_DE_MATRICULA INT NOT NULL, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL);


INSERT INTO ODONTOLOGOS(NUMERO_DE_MATRICULA, NOMBRE, APELLIDO) VALUES (103, 'Sergio', 'Marquez'), (104, 'Mauro', 'Mascheroni'), (105, 'Martin', 'Pardo');
